# Generated by Django 4.2.6 on 2023-10-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savvydata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
        migrations.DeleteModel(
            name='TestToken',
        ),
    ]
