# Generated by Django 4.2.6 on 2023-10-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savvydata', '0002_delete_login_delete_signup_delete_testtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='restaurant_id',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
